Models/Manutencao.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MiniFrota.Models
{
    public class Manutencao
    {
        [Key]
        public int ManutencaoId { get; set; }

        [DataType(DataType.Text)]
        [DisplayFormat(DataFormatString = "{0: dd/MM/yyyy }", ApplyFormatInEditMode = true)]
        [Display(Name = "DataManutencao")]
        public DateTime DataManutencao { get; set; }

        [Required(ErrorMessage = "Informe o Km do dia da manutenção")]
        [Display(Name = "KmDiaManutencao")]
        public long KmDiaManutencao { get; set; }

        [DataType(DataType.Text)]
        [DisplayFormat(DataFormatString = "{0: dd/MM/yyyy }", ApplyFormatInEditMode = true)]
        [Display(Name = "DataProximaManutencao")]
        public DateTime DataProximaManutencao { get; set; }

        [Required(ErrorMessage = "Informe o valor da manutenção")]
        [Display(Name = "ValorManutencao")]
        [Column(TypeName ="decimal(10,2)")]
        [Range(1.999,99,ErrorMessage ="O preço deve estar entre 1 e 9999,99")]
        public decimal ValorManutencao { get; set; }

        [Required(ErrorMessage = "Informe as peças substituídas")]
        [Display(Name = "pecasSubstituidas")]
        public string pecasSubstituidas { get; set; }
        
        [Required(ErrorMessage = "Informe a descrição do serviço")]
        [Display(Name = "DescricaoServico")]
        public string  DescricaoServico { get; set; }
        
    }
}

Controllers/ManutencaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MiniFrota.Context;
using MiniFrota.Models;

namespace MiniFrota.Controllers
{
    public class ManutencaoController : Controller
    {
        private readonly ILogger<ManutencaoController> _logger;
        private readonly AppDbContext _context;

        public ManutencaoController(ILogger<ManutencaoController> logger, AppDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index() => View();

            [HttpPost]
        public IActionResult Index(Manutencao manutencao)
        {
            if (ModelState.IsValid)
            {
                _context.Manutencoes.Add(manutencao);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            
            return View(manutencao);
        }

        public IActionResult Listar()
        {
            var manutencoes = _context.Manutencoes.ToList();
            return View(manutencoes);
        }

        public IActionResult Editar(int id)
        {
            var manutencoes = _context.Manutencoes.Find(id);
            if (manutencoes == null)
            {
                return NotFound();
            }

            return View(manutencoes);
        }

        [HttpPost]
        public IActionResult Editar(Manutencao manutencao)
        {
            if (ModelState.IsValid)
            {
                _context.Manutencoes.Update(manutencao);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(manutencao);
        }

        public IActionResult Excluir(int id)
        {
            var manutencao = _context.Manutencoes.Find(id);
            if (manutencao == null)
            {
                return NotFound();
            }

            _context.Manutencoes.Remove(manutencao);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/MultaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MiniFrota.Context;
using MiniFrota.Models;

namespace MiniFrota.Controllers
{
    public class MultaController : Controller
    {
        private readonly ILogger<MultaController> _logger;
        private readonly AppDbContext _context;

        public MultaController(ILogger<MultaController> logger, AppDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index() => View();

        [HttpPost]
        public IActionResult Index(Multa multa)
        {
            if (ModelState.IsValid)
            {
                _context.Multas.Add(multa);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            
            return View(multa);
        }

        public IActionResult Listar()
        {
            var multas = _context.Multas.ToList();
            return View(multas);
        }

        public IActionResult EditarPorId(int id)
        {
            var multa = _context.Multas.Find(id);
            if (multa == null)
            {
                return NotFound();
            }

            return View(multa);
        }

        [HttpPost]
        public IActionResult Editar(Multa multa)
        {
            if (ModelState.IsValid)
            {
                _context.Multas.Update(multa);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(multa);
        }

        public IActionResult Excluir(int id)
        {
            var multa = _context.Multas.Find(id);
            if (multa == null)
            {
                return NotFound();
            }

            _context.Multas.Remove(multa);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/SeguroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MiniFrota.Context;
using MiniFrota.Models;

namespace MiniFrota.Controllers
{
    public class SeguroController : Controller
    {
        private readonly ILogger<SeguroController> _logger;
        private readonly AppDbContext _context;

        public SeguroController(ILogger<SeguroController> logger, AppDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index() => View();

          [HttpPost]
        public IActionResult Index(Seguro seguro)
        {
            if (ModelState.IsValid)
            {
                _context.Seguros.Add(seguro);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            
            return View(seguro);
        }

        public IActionResult Listar()
        {
            var seguros = _context.Seguros.ToList();
            return View(seguros);
        }

        public IActionResult Editar(int id)
        {
            var seguro = _context.Seguros.Find(id);
            if (seguro == null)
            {
                return NotFound();
            }

            return View(seguro);
        }

        [HttpPost]
        public IActionResult Editar(Seguro seguro)
        {
            if (ModelState.IsValid)
            {
                _context.Seguros.Update(seguro);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(seguro);
        }

        public IActionResult Excluir(int id)
        {
            var seguro = _context.Seguros.Find(id);
            if (seguro == null)
            {
                return NotFound();
            }

            _context.Seguros.Remove(seguro);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        
    }
}

Controllers/SinistroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MiniFrota.Context;
using MiniFrota.Models;

namespace MiniFrota.Controllers
{
    public class SinistroController : Controller
    {
        private readonly ILogger<SinistroController> _logger;
        private readonly AppDbContext _context;

        public SinistroController(ILogger<SinistroController> logger, AppDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index() => View();

        [HttpPost]
        public IActionResult Index(Sinistro sinistro)
        {
            if (ModelState.IsValid)
            {
                _context.Sinistros.Add(sinistro);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            
            return View(sinistro);
        }

        public IActionResult Listar()
        {
            var sinistro = _context.Sinistros.ToList();
            return View(sinistro);
        }

        public IActionResult Editar(int id)
        {
            var sinistro = _context.Sinistros.Find(id);
            if (sinistro == null)
            {
                return NotFound();
            }

            return View(sinistro);
        }

        [HttpPost]
        public IActionResult Editar(Sinistro sinistro)
        {
            if (ModelState.IsValid)
            {
                _context.Sinistros.Update(sinistro);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(sinistro);
        }

        public IActionResult Excluir(int id)
        {
            var sinistro = _context.Sinistros.Find(id);
            if (sinistro == null)
            {
                return NotFound();
            }

            _context.Sinistros.Remove(sinistro);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/VeiculoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MiniFrota.Context;
using MiniFrota.Models;

namespace MiniFrota.Controllers
{
    public class VeiculoController : Controller
    {
        private readonly ILogger<VeiculoController> _logger;
        private readonly AppDbContext _context;

        public VeiculoController(ILogger<VeiculoController> logger, AppDbContext context) 
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Veiculo veiculo)
        {
            if (ModelState.IsValid)
            {
                _context.Veiculos.Add(veiculo);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            
            return View(veiculo);
        }
            public IActionResult Listar()
        {
            var veiculos = _context.Veiculos.ToList();
            return View(veiculos);
        }

        public IActionResult Editar(string placa)
        {
            var veiculo = _context.Veiculos.Find(placa);
            if (veiculo == null)
            {
                return NotFound();
            }

            return View(veiculo);
        }

        [HttpPost]
        public IActionResult Editar(Veiculo veiculo)
        {
            if (ModelState.IsValid)
            {
                _context.Veiculos.Update(veiculo);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(veiculo);
        }

        public IActionResult Excluir(string placa)
        {
            var veiculo = _context.Veiculos.Find(placa);
            if (veiculo == null)
            {
                return NotFound();
            }

            _context.Veiculos.Remove(veiculo);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Manutencao/Index.cshtml
@model MiniFrota.Models.Manutencao;
@{
    ViewData["Title"] = "Manutenção";
}

    <div class="container-fluid">
        <div class="row">
            <!-- Menu Lateral -->
            <div class="col-md-2 bg-dark text-white" style="border-radius: 5px;">
                <h3 class="text-center mt-3" >Menu </h3>
                <ul class="nav flex-column mt-4">
                    <li class="nav-item">
                        <a class="nav-link text-white"asp-controller="Veiculo" asp-action="Index">Veículo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Multa" asp-action="Index">Multa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white"asp-controller="Motorista" asp-action="Index">Motorista</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link text-white"asp-controller="Manutencao" asp-action="Index">Manutenção</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#">Administrador</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Abastecer" asp-action="Index">Abastecer</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Emplacamento" asp-action="Index">Emplacamento</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white"asp-controller="Seguro" asp-action="Index">Seguro</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Sinistro" asp-action="Index">Sinistro</a>
                    </li>
                </ul>
        </div>
            
            <!-- Conteúdo Principal -->
            <div class="col-md-9">
                <h1>Manutenção</h1>
                <form method="post">
  <div class="mb-3 col-9">
    <label asp-for="DataManutencao" class="form-label">Data da Manutenção</label>
    <input asp-for="DataManutencao" type="date" class="form-control" id="DataManutencao" aria-describedby="textHelp">
  </div>
  <div class="mb-3 col-9">
    <label asp-for="KmDiaManutencao" class="form-label">Km dia Manutenção</label>
    <input asp-for="KmDiaManutencao" type="number" class="form-control" id="KmDiaManutencao" aria-describedby="textHelp">
  </div>
  <div class="mb-3 col-9">
    <label asp-for="DataProximaManutencao" class="form-label">Data próxima revisão</label>
    <input asp-for="DataProximaManutencao" type="date" class="form-control" id="DataProximaManutencao" aria-describedby="textHelp">
  </div>
  <div class="mb-3 col-9">
    <label asp-for="ValorManutencao" class="form-label">Valor</label>
    <input asp-for="ValorManutencao" type="number" class="form-control" id="ValorManutencao" aria-describedby="textHelp">
  </div>
  <div class="mb-3 col-9">
    <label asp-for="pecasSubstituidas" class="form-label">Peças substituidas</label>
    <input asp-for="pecasSubstituidas" type="text" class="form-control" id="pecasSubstituidas" aria-describedby="textHelp">
  </div>
   <div class="mb-3 col-9">
    <label asp-for="DescricaoServico" class="form-label">Descrição serviços realizados</label>
    <input asp-for="DescricaoServico" type="text" class="form-control" id="DescricaoServico" aria-describedby="textHelp">
  </div>

  <button type="submit" class="btn btn-success" style="margin-right: 2.8rem;" asp-action="Index" value="Index" asp-controller="Manutencao">Cadastrar</button>
  <button type="submit" class="btn btn-info" style="margin: 2.8rem;" asp-action="Listar" value="Listar" asp-controller="Manutencao">Listar</button>
  <button type="submit" class="btn btn-warning" style="margin: 2.8rem;">Alterar</button>
  <button type="submit" class="btn btn-danger" style="margin: 2.8rem;">Deletar</button>

  
</form>
                <!-- Aqui você pode adicionar o conteúdo específico de cada item do menu -->
            </div>
        </div>
    </div>
    

Views/Manutencao/Listar.cshtml
@model IEnumerable<MiniFrota.Models.Manutencao>;
@{
    ViewData["Title"] = "Lista de Manutenções";
}

<table class="table table-success table-hover">
  <thead>
    @* Parte superior da lista, cabeçalho *@
    <tr>
      <th scope="col">
        @Html.DisplayNameFor(model => model.ManutencaoId)
      </th>
      <th scope="col">
        @Html.DisplayNameFor(model => model.KmDiaManutencao)
      </th>
      <th scope="col">
         @Html.DisplayNameFor(model => model.DataProximaManutencao)
      </th>
      <th scope="col">
         @Html.DisplayNameFor(model => model.ValorManutencao)
      </th>
      <th scope="col">
         @Html.DisplayNameFor(model => model.pecasSubstituidas)
      </th>
      <th scope="col">
         @Html.DisplayNameFor(model => model.DescricaoServico)
      </th>
          @* <th scope="col">
         @Html.DisplayNameFor(model => model.Motoristas)
      </th> *@
    </tr>
  </thead>
  <tbody class="table table-success table-hover">

    @foreach (var item in Model)
    {
      <tr>
        <th scope="row">
          @Html.DisplayFor(model => item.ManutencaoId)
        </th>
        <th scope="row">
          @Html.DisplayFor(model => item.DataManutencao)
        </th>
        <td>
          @Html.DisplayFor(model => item.KmDiaManutencao)
        </td>
        <td>
           @Html.DisplayFor(model => item.DataProximaManutencao)
        </td>
        <td>
           @Html.DisplayFor(model => item.ValorManutencao)
        </td>
        <td>
           @Html.DisplayFor(model => item.pecasSubstituidas)
        </td>
        <td>
           @Html.DisplayFor(model => item.DescricaoServico)
        </td>
        @* <td>
           @Html.DisplayFor(model => item.Motoristas)
        </td> *@
        <td>
          <a type="submit" class="btn btn-warning"  asp-action="Editar" asp-route-id="@item.ManutencaoId" asp-controller="Manutencao">Alterar</a>
        </td>
        <td>
          <a type="submit" class="btn btn-danger"  asp-action="Excluir" value="Excluir" asp-route-id="@item.ManutencaoId" asp-controller="Manutencao" >Deletar</a>
        </td>
      </tr>
    }
  </tbody>
</table>