Models/Emplacamento.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization.Infrastructure;

namespace MiniFrota.Models
{
    public class Emplacamento 
    {
        [Key]
        [Required(ErrorMessage = "Informe a placa do veiculo")]
        [Display(Name = "Placas")]
        public string Placas { get; set; }

        [Required(ErrorMessage = "Informe a data do emplacamento")]
        [DataType(DataType.Text)]
        [DisplayFormat(DataFormatString = "{0: dd/MM/yyyy }", ApplyFormatInEditMode = true)]
        [DisplayName("DataVencimento")]
        public DateTime DataVencimento { get; set; }

        [Required(ErrorMessage = "Informe o valor emplacamento")]
        [Display(Name = "ValorEmplacamento")]
        [Column(TypeName ="decimal(10,2)")]
        public decimal ValorEmplacamento { get; set; }
    }
}

Controllers/AbastecerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MiniFrota.Context;
using MiniFrota.Models;

namespace MiniFrota.Controllers
{
    public class AbastecerController : Controller   
    {
        private readonly ILogger<AbastecerController> _logger;
        private readonly AppDbContext _context;

        public AbastecerController(ILogger<AbastecerController> logger, AppDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Abastecer abastecer)
        {
            if (ModelState.IsValid)
            {
                _context.Combustiveis.Add(abastecer);
                _context.SaveChanges();
                
                return RedirectToAction(nameof(Index));
            }

            return View(abastecer);
        }   

         public IActionResult Listar()
        {
            var abastecer = _context.Combustiveis.ToList();
            return View(abastecer);
        }

        public IActionResult EditarPorId(int AbastecerId)
        {
            var abastecer = _context.Combustiveis.Find(AbastecerId);
            if (abastecer == null)
            {
                return NotFound();
            }

            return View(abastecer);
        }

        [HttpPost]
        public IActionResult Editar(Abastecer abastecer)
        {
            if (ModelState.IsValid)
            {
                _context.Combustiveis.Update(abastecer);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(abastecer);
        }

         public IActionResult Excluir(int id)
        {
            var abastecimento = _context.Combustiveis.Find(id);
            if (abastecimento == null)
            {
                return NotFound();
            }

            _context.Combustiveis.Remove(abastecimento);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

    }
}

Controllers/EmplacamentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MiniFrota.Context;
using MiniFrota.Models;

namespace MiniFrota.Controllers
{
    public class EmplacamentoController : Controller
    {
        private readonly ILogger<Emplacamento> _logger;
        private readonly AppDbContext _context;

        public EmplacamentoController(ILogger<Emplacamento> logger, AppDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Emplacamento emplacamento)
        {
            if (ModelState.IsValid)
            {
                _context.Emplacamentos.Add(emplacamento);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            
            return View(emplacamento);
        }

         public IActionResult Listar()
        {
            var emplacamentos = _context.Emplacamentos.ToList();
            return View(emplacamentos);
        }
 
        public IActionResult Editar(string placa)
        {
            var emplacamento = _context.Emplacamentos.Find(placa);
            if (emplacamento== null)
            {
                return NotFound();
            }

            return View(emplacamento);
        }

        [HttpPost]
        public IActionResult Editar(Emplacamento emplacamento)
        {
            if (ModelState.IsValid)
            {
                _context.Emplacamentos.Update(emplacamento);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(emplacamento);
        }

        public IActionResult Excluir(string placa)
        {
            var emplacamento = _context.Emplacamentos.Find(placa);
            if (emplacamento == null)
            {
                return NotFound();
            }

            _context.Emplacamentos.Remove(emplacamento);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/MultaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MiniFrota.Context;
using MiniFrota.Models;

namespace MiniFrota.Controllers
{
    public class MultaController : Controller
    {
        private readonly ILogger<MultaController> _logger;
        private readonly AppDbContext _context;

        public MultaController(ILogger<MultaController> logger, AppDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index() => View();

        [HttpPost]
        public IActionResult Index(Multa multa)
        {
            if (ModelState.IsValid)
            {
                _context.Multas.Add(multa);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            
            return View(multa);
        }

        public IActionResult Listar()
        {
            var multas = _context.Multas.ToList();
            return View(multas);
        }

        public IActionResult EditarPorId(int id)
        {
            var multa = _context.Multas.Find(id);
            if (multa == null)
            {
                return NotFound();
            }

            return View(multa);
        }

        [HttpPost]
        public IActionResult Editar(Multa multa)
        {
            if (ModelState.IsValid)
            {
                _context.Multas.Update(multa);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(multa);
        }

        public IActionResult Excluir(int id)
        {
            var multa = _context.Multas.Find(id);
            if (multa == null)
            {
                return NotFound();
            }

            _context.Multas.Remove(multa);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/SeguroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MiniFrota.Context;
using MiniFrota.Models;

namespace MiniFrota.Controllers
{
    public class SeguroController : Controller
    {
        private readonly ILogger<SeguroController> _logger;
        private readonly AppDbContext _context;

        public SeguroController(ILogger<SeguroController> logger, AppDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index() => View();

          [HttpPost]
        public IActionResult Index(Seguro seguro)
        {
            if (ModelState.IsValid)
            {
                _context.Seguros.Add(seguro);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            
            return View(seguro);
        }

        public IActionResult Listar()
        {
            var seguros = _context.Seguros.ToList();
            return View(seguros);
        }

        public IActionResult Editar(int id)
        {
            var seguro = _context.Seguros.Find(id);
            if (seguro == null)
            {
                return NotFound();
            }

            return View(seguro);
        }

        [HttpPost]
        public IActionResult Editar(Seguro seguro)
        {
            if (ModelState.IsValid)
            {
                _context.Seguros.Update(seguro);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(seguro);
        }

        public IActionResult Excluir(int id)
        {
            var seguro = _context.Seguros.Find(id);
            if (seguro == null)
            {
                return NotFound();
            }

            _context.Seguros.Remove(seguro);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        
    }
}

Controllers/VeiculoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MiniFrota.Context;
using MiniFrota.Models;

namespace MiniFrota.Controllers
{
    public class VeiculoController : Controller
    {
        private readonly ILogger<VeiculoController> _logger;
        private readonly AppDbContext _context;

        public VeiculoController(ILogger<VeiculoController> logger, AppDbContext context) 
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Veiculo veiculo)
        {
            if (ModelState.IsValid)
            {
                _context.Veiculos.Add(veiculo);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            
            return View(veiculo);
        }
            public IActionResult Listar()
        {
            var veiculos = _context.Veiculos.ToList();
            return View(veiculos);
        }

        public IActionResult Editar(string placa)
        {
            var veiculo = _context.Veiculos.Find(placa);
            if (veiculo == null)
            {
                return NotFound();
            }

            return View(veiculo);
        }

        [HttpPost]
        public IActionResult Editar(Veiculo veiculo)
        {
            if (ModelState.IsValid)
            {
                _context.Veiculos.Update(veiculo);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(veiculo);
        }

        public IActionResult Excluir(string placa)
        {
            var veiculo = _context.Veiculos.Find(placa);
            if (veiculo == null)
            {
                return NotFound();
            }

            _context.Veiculos.Remove(veiculo);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Emplacamento/Editar.cshtml
@model MiniFrota.Models.Emplacamento;
@{
    ViewData["Title"] = "Editar Emplacamento";
}

    <div class="container-fluid">
        <div class="row">
            <!-- Menu Lateral -->
            <div class="col-md-2 bg-dark text-white" style="border-radius: 5px;">
                <h3 class="text-center mt-3" >Menu </h3>
                <ul class="nav flex-column mt-4">
                    <li class="nav-item">
                        <a class="nav-link text-white"asp-controller="Veiculo" asp-action="Index">Veículo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white"asp-controller="Multa" asp-action="Index">Multa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white"asp-controller="Motorista" asp-action="Index">Motorista</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white"asp-controller="Manutencao" asp-action="Index">Manutenção</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#">Administrador</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Abastecer" asp-action="Index">Abastecer</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Emplacamento" asp-action="Index">Emplacamento</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Seguro" asp-action="Index">Seguro</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#">Sinistro</a>
                    </li>
                </ul>
        </div>
            
            <!-- Conteúdo Principal -->
            <div class="col-md-9">
                <h1>Emplacamento</h1>
<form method="post">
  <div class="mb-3 col-9">
    <label asp-for="Placas" class="form-label">Placa do Veículo</label>
    <input asp-for="Placas" type="Text" class="form-control" id="Placas" aria-describedby="textHelp">
  </div>
  <div class="mb-3 col-9">
    <label asp-for="DataVencimento" class="form-label">Data do vencimento</label>
    <input asp-for="DataVencimento" type="Date" class="form-control" id="DataVencimento" aria-describedby="textHelp">
  </div>
  <div class="mb-3 col-9">
    <label asp-for="ValorEmplacamento" class="form-label">Valor do emplacamento</label>
    <input asp-for="ValorEmplacamento" type="number" class="form-control" id="ValorEmplacamento" aria-describedby="textHelp">
  </div>
  <button type="submit" class="btn btn-success" style="margin-right: 2.8rem;" asp-action="Index" value="Index" asp-controller="Emplacamento">Cadastrar</button>
  <button type="submit" class="btn btn-info" style="margin: 2.8rem;" asp-action="Listar" value="Listar" asp-controller="Emplacamento">Listar</button>
  <button type="submit" class="btn btn-warning" style="margin: 2.8rem;">Alterar</button>
  <button type="submit" class="btn btn-danger" style="margin: 2.8rem;">Deletar</button>

  
</form>
                <!-- Aqui você pode adicionar o conteúdo específico de cada item do menu -->
            </div>
        </div>
    </div>
    

Views/Emplacamento/Index.cshtml
@model MiniFrota.Models.Emplacamento;
@{
    ViewData["Title"] = "Emplacamento";
}

    <div class="container-fluid">
        <div class="row">
            <!-- Menu Lateral -->
            <div class="col-md-2 bg-dark text-white" style="border-radius: 5px;">
                <h3 class="text-center mt-3" >Menu </h3>
                <ul class="nav flex-column mt-4">
                    <li class="nav-item">
                        <a class="nav-link text-white"asp-controller="Veiculo" asp-action="Index">Veículo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white"asp-controller="Multa" asp-action="Index">Multa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white"asp-controller="Motorista" asp-action="Index">Motorista</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white"asp-controller="Manutencao" asp-action="Index">Manutenção</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#">Administrador</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Abastecer" asp-action="Index">Abastecer</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Emplacamento" asp-action="Index">Emplacamento</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Seguro" asp-action="Index">Seguro</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#">Sinistro</a>
                    </li>
                </ul>
        </div>
            
            <!-- Conteúdo Principal -->
            <div class="col-md-9">
                <h1>Emplacamento</h1>
<form method="post">
  <div class="mb-3 col-9">
    <label asp-for="Placas" class="form-label">Placa do Veículo</label>
    <input asp-for="Placas" type="Text" class="form-control" id="Placas" aria-describedby="textHelp">
  </div>
  <div class="mb-3 col-9">
    <label asp-for="DataVencimento" class="form-label">Data do vencimento</label>
    <input asp-for="DataVencimento" type="Date" class="form-control" id="DataVencimento" aria-describedby="textHelp">
  </div>
  <div class="mb-3 col-9">
    <label asp-for="ValorEmplacamento" class="form-label">Valor do emplacamento</label>
    <input asp-for="ValorEmplacamento" type="number" class="form-control" id="ValorEmplacamento" aria-describedby="textHelp">
  </div>
  <button type="submit" class="btn btn-success" style="margin-right: 2.8rem;" asp-action="Index" value="Index" asp-controller="Emplacamento">Cadastrar</button>
  <button type="submit" class="btn btn-info" style="margin: 2.8rem;" asp-action="Listar" value="Listar" asp-controller="Emplacamento">Listar</button>
  <button type="submit" class="btn btn-warning" style="margin: 2.8rem;">Alterar</button>
  <button type="submit" class="btn btn-danger" style="margin: 2.8rem;">Deletar</button>

  
</form>
                <!-- Aqui você pode adicionar o conteúdo específico de cada item do menu -->
            </div>
        </div>
    </div>
    

Views/Emplacamento/Listar.cshtml
@model IEnumerable<MiniFrota.Models.Emplacamento>;
@{
    ViewData["Title"] = "Lista de Emplacamento";
}

<table class="table table-success table-hover">
  <thead>
    @* Parte superior da lista, cabeçalho *@
    <tr>
      <th scope="col">
        @Html.DisplayNameFor(model => model.Placas)
      </th>
      <th scope="col">
        @Html.DisplayNameFor(model => model.DataVencimento)
      </th>
      <th scope="col">
         @Html.DisplayNameFor(model => model.ValorEmplacamento)
      </th>
          @* <th scope="col">
         @Html.DisplayNameFor(model => model.Motoristas)
      </th> *@
    </tr>
  </thead>
  <tbody class="table table-success table-hover">

    @foreach (var item in Model)
    {
      <tr>
        <th scope="row">
          @Html.DisplayFor(model => item.Placas)
        </th>
        <td>
          @Html.DisplayFor(model => item.DataVencimento)
        </td>
        <td>
           @Html.DisplayFor(model => item.ValorEmplacamento)
        </td>
        @* <td>
           @Html.DisplayFor(model => item.Motoristas)
        </td> *@
        <td>
          <a class="btn btn-warning" asp-action="Editar" asp-route-id="@item.Placas">Alterar</a>
        </td>
        <td>
          <a type="submit" class="btn btn-danger"  asp-action="Excluir" value="Excluir" asp-route-id="@item.Placas">Deletar</a>
        </td>
      </tr>
    }
  </tbody>
</table>